{
 "title": "cloudnative-pg pgBouncer",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Avg. Sent/Recv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "cnpg_pgbouncer_stats_avg_recv", "legendFormat": "{{database}}_recv" },
    { "expr": "cnpg_pgbouncer_stats_avg_sent", "legendFormat": "{{database}}_sent" }
   ]
  },
  {
   "title": "Avg. xact count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "cnpg_pgbouncer_stats_avg_xact_count",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Avg. Query Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "cnpg_pgbouncer_stats_avg_query_count",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Avg. Query Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "cnpg_pgbouncer_stats_avg_query_time",
     "legendFormat": "{{database}}"
    }
   ]
  }
 ]
}