{
 "title": "qui",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(qbittorrent_instance_connection_status, instance_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connection Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_instance_connection_status{instance_name=\"$instance\"}",
     "legendFormat": "Connection Status"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "qbittorrent_download_speed_bytes_per_second{instance_name=\"$instance\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "qbittorrent_upload_speed_bytes_per_second{instance_name=\"$instance\"}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Total Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "qbittorrent_alltime_download_bytes{instance_name=\"$instance\"}",
     "legendFormat": "Total Download"
    },
    {
     "expr": "qbittorrent_alltime_upload_bytes{instance_name=\"$instance\"}",
     "legendFormat": "Total Upload"
    }
   ]
  },
  {
   "title": "Session Data",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "qbittorrent_session_download_bytes{instance_name=\"$instance\"}",
     "legendFormat": "Session Download"
    },
    {
     "expr": "qbittorrent_session_upload_bytes{instance_name=\"$instance\"}",
     "legendFormat": "Session Upload"
    }
   ]
  },
  {
   "title": "Torrent States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "qbittorrent_torrents_checking{instance_name=\"$instance\"}",
     "legendFormat": "Checking"
    },
    {
     "expr": "qbittorrent_torrents_downloading{instance_name=\"$instance\"}",
     "legendFormat": "Downloading"
    },
    {
     "expr": "qbittorrent_torrents_error{instance_name=\"$instance\"}",
     "legendFormat": "Error"
    },
    {
     "expr": "qbittorrent_torrents_paused{instance_name=\"$instance\"}",
     "legendFormat": "Paused"
    },
    {
     "expr": "qbittorrent_torrents_seeding{instance_name=\"$instance\"}",
     "legendFormat": "Seeding"
    }
   ]
  }
 ]
}